### model
model_name_or_path: microsoft/phi-4

### method
stage: dpo
do_train: true
finetuning_type: full
# finetuning_type: lora
# lora_rank: 8
# lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: venus_runtime_dpo, venus_memory_dpo
template: default
max_samples: 50000
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: {root_path}/mingzhe_checkpoints/phi_4_14b_0120_dpo_ds3_2e-6
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 200
